/** Living inventory of every external API operation this codebase calls — update this whenever a
 *  client (server/src/clients/*.client.ts) gains/changes an operation, same discipline as
 *  architecture-diagram.ts. Source of truth for the "Referência de APIs" section on the
 *  Arquitetura page. Each `endpoint` string is copied verbatim from the actual code, not
 *  paraphrased, so this stays checkable against the client files. */

export type ApiOperationKind = "read" | "write";

export interface ApiOperation {
  name: string;
  method: string;
  endpoint: string;
  kind: ApiOperationKind;
  fields: string;
  purpose: string;
  caveat?: string;
}

export interface ApiSystem {
  key: string;
  title: string;
  baseUrl: string;
  auth: string;
  retry: string;
  operations: ApiOperation[];
}

export const API_REFERENCE: ApiSystem[] = [
  {
    key: "vtex",
    title: "VTEX (Catalog + Search)",
    baseUrl: "https://{account}.{environment}.com.br/api/catalog (privada) e /api/catalog_system/pub (pública)",
    auth: "Headers X-VTEX-API-AppKey / X-VTEX-API-AppToken",
    retry: "requestWithRetry compartilhado — até 4 tentativas, só em 429/5xx, respeita Retry-After",
    operations: [
      {
        name: "fetchProduct",
        method: "GET",
        endpoint: "/pvt/product/{productId}",
        kind: "read",
        fields: "Id, Name, Description, CategoryId, LinkId, SkuIds, e demais campos do produto",
        purpose: "Produto completo — base de getProduct() e do padrão ler→mesclar→escrever de todo write.",
      },
      {
        name: "fetchSku",
        method: "GET",
        endpoint: "/pvt/stockkeepingunit/{skuId}",
        kind: "read",
        fields: "Id, ProductId, NameComplete, RefId, Images[].ImageUrl/ImageText",
        purpose: "Imagens e código de referência (SKU) do primeiro SKU do produto.",
      },
      {
        name: "fetchProductSpecifications",
        method: "GET",
        endpoint: "/catalog_system/pub/products/search?fq=productId:{id}",
        kind: "read",
        fields: "allSpecifications (Marca, Material, Acabamento, Bitola, Dimensões, ...), brand, categories",
        purpose: "Características/Especificações do produto (attributes) + marca + trilha de categoria.",
        caveat: "Nunca lança erro — falha retorna {} silenciosamente, pra não quebrar o sync de um produto por um lookup ruim.",
      },
      {
        name: "listProducts",
        method: "GET",
        endpoint: "/catalog_system/pub/products/search?_from&_to&ft&fq",
        kind: "read",
        fields: "productId, productName, categorias, marca, imagem, referenceId",
        purpose: "Listagem paginada com busca/filtro pra tela de Produtos.",
      },
      {
        name: "listFilterOptions",
        method: "GET",
        endpoint: "/catalog_system/pub/category/tree/3 + /brand/list",
        kind: "read",
        fields: "Árvore de categorias completa; marcas ativas",
        purpose: "Popula os filtros de categoria/marca da tela de Produtos.",
      },
      {
        name: "listCategoryTree",
        method: "GET",
        endpoint: "/catalog_system/pub/category/tree/3",
        kind: "read",
        fields: "Mesma árvore de listFilterOptions, mas mantendo o breadcrumb (\"Casa > Banheiro > Torneiras\") e se o nó é folha (onde produtos de fato se classificam)",
        purpose: "Alimenta category_nodes — base pra listar em que Subcategoria/Categoria dá pra adicionar link de referência ou ver campos aceitos, mesmo antes de qualquer produto existir ali.",
      },
      {
        name: "getCategoryFieldDefinitions",
        method: "GET",
        endpoint: "/catalog_system/pub/specification/field/listTreeByCategoryId/{categoryId}",
        kind: "read",
        fields: "Name, FieldId, IsActive, IsStockKeepingUnit (filtrado pra false — campo do produto, não do SKU)",
        purpose: "Quais campos de especificação a VTEX aceita nessa categoria — consultado antes de gerar, pra IA nunca propor um atributo sem onde a plataforma salvar. Nunca cobre preço/estoque/categoria, que são APIs inteiramente separadas.",
        caveat: "Achado testando contra a conta real (2026-08-04): o endpoint 'gêmeo' listByCategoryId (sem 'Tree') voltava [] mesmo pra categoria com campos configurados no admin — listTreeByCategoryId é o que realmente retorna.",
      },
      {
        name: "updateProductFields",
        method: "PUT",
        endpoint: "/pvt/product/{productId}",
        kind: "write",
        fields: "Produto completo (fetch fresco) mesclado só com as chaves alteradas",
        purpose: "Base de updateProductDescription/updateProductSeo.",
        caveat: "Corrigido em 2026-08-04: este PUT NÃO faz merge parcial — sempre busca o produto inteiro antes de escrever, senão campos omitidos voltam vazios.",
      },
      {
        name: "updateProductDescription",
        method: "PUT",
        endpoint: "/pvt/product/{productId} (via updateProductFields)",
        kind: "write",
        fields: "Description",
        purpose: "Publica a descrição enriquecida (+ bullets/specs/FAQ/CTA mesclados como HTML).",
      },
      {
        name: "updateProductSeo",
        method: "PUT",
        endpoint: "/pvt/product/{productId} (via updateProductFields)",
        kind: "write",
        fields: "Title, MetaTagDescription",
        purpose: "Publica título e meta description otimizados para SEO.",
      },
      {
        name: "updateProductTags",
        method: "—",
        endpoint: "no-op",
        kind: "write",
        fields: "—",
        purpose: "VTEX não tem campo de tags nativo sem tocar na árvore de categoria — fica só no CatalogIA.",
      },
      {
        name: "getKnownAttributeFields",
        method: "—",
        endpoint: "no-op (retorna [])",
        kind: "read",
        fields: "—",
        purpose: "VTEX não tem conceito de metafield — normalização de atributos fica só no CatalogIA por ora.",
      },
      {
        name: "addProductImage",
        method: "POST",
        endpoint: "/pvt/stockkeepingunit/{skuId}/file",
        kind: "write",
        fields: "IsMain, Label, Text, Url",
        purpose: "Publica uma foto gerada por IA como imagem real do produto — VTEX busca os bytes da Url.",
      },
      {
        name: "updateSkuImageAltText",
        method: "PUT",
        endpoint: "/pvt/stockkeepingunit/{skuId}/file/{imageId}",
        kind: "write",
        fields: "Text",
        purpose: "Publica alt-text gerado por IA numa imagem existente.",
      },
      {
        name: "testConnection",
        method: "GET",
        endpoint: "/api/catalog_system/pvt/brand/list",
        kind: "read",
        fields: "—",
        purpose: "Valida a credencial VTEX salva no painel de Integrações.",
      },
    ],
  },
  {
    key: "shopify",
    title: "Shopify (Admin GraphQL)",
    baseUrl: "https://{shopDomain}/admin/api/2026-01/graphql.json",
    auth: "Header X-Shopify-Access-Token",
    retry: "requestWithRetry compartilhado — até 4 tentativas, só em 429/5xx, respeita Retry-After",
    operations: [
      {
        name: "getProduct",
        method: "query",
        endpoint: "GetProduct($id: ID!)",
        kind: "read",
        fields: "title, descriptionHtml, productType, vendor, media[], variants[], metafields[], collections[]",
        purpose: "Produto completo, incluindo metafields já cadastrados.",
        caveat: "Metafields do tipo referência (gid://...) são descartados — mandar o id bruto pra IA seria peor que omitir.",
      },
      {
        name: "listProducts",
        method: "query",
        endpoint: "ListProducts($first, $query, $after)",
        kind: "read",
        fields: "id, title, handle, productType, vendor, featuredImage, sku, collections",
        purpose: "Listagem paginada por cursor pra tela de Produtos.",
        caveat: "Paginação por cursor é presa à instância do client — corrigido bug que reprocessava a página 1 em todo run de 'otimização total'.",
      },
      {
        name: "listFilterOptions",
        method: "query",
        endpoint: "ListFilterOptions (collections + productVendors)",
        kind: "read",
        fields: "Coleções (categoria real do Shopify) e vendors (marcas)",
        purpose: "Popula os filtros de categoria/marca — verificado ao vivo contra loja real.",
      },
      {
        name: "updateProductDescription",
        method: "mutation",
        endpoint: "productUpdate → descriptionHtml",
        kind: "write",
        fields: "descriptionHtml",
        purpose: "Publica a descrição (+ bullets/specs/FAQ/CTA mesclados como HTML).",
      },
      {
        name: "updateProductSeo",
        method: "mutation",
        endpoint: "productUpdate → seo{title,description}",
        kind: "write",
        fields: "seo.title, seo.description",
        purpose: "Publica título e meta description otimizados para SEO.",
      },
      {
        name: "updateProductTags",
        method: "mutation",
        endpoint: "productUpdate → tags",
        kind: "write",
        fields: "tags[] (substitui a lista inteira)",
        purpose: "Publica as tags de navegação/filtro geradas.",
      },
      {
        name: "fetchSafeMetafieldDefinitions / getKnownAttributeFields",
        method: "query",
        endpoint: "metafieldDefinitions(ownerType: PRODUCT)",
        kind: "read",
        fields: "namespace, key, name, type — só tipos escalares seguros",
        purpose: "Consultado ANTES da geração — parâmetros já cadastrados (Category/Product metafields) que a IA deve preferir preencher.",
        caveat: "Tipos referência/lista (Color/Material padrão) ficam de fora de propósito — resolver GID de taxonomia não foi implementado.",
      },
      {
        name: "createAttributeField",
        method: "mutation",
        endpoint: "metafieldDefinitionCreate",
        kind: "write",
        fields: "name, namespace, key (slug), type, ownerType",
        purpose: "Cria um metafield novo só quando nenhum existente casa com o conceito (nunca duplica).",
      },
      {
        name: "updateProductMetafields",
        method: "mutation",
        endpoint: "metafieldsSet",
        kind: "write",
        fields: "namespace, key, type, value por entrada",
        purpose: "Escreve attributes_patch (campo já existente ou recém-criado) e structured_data/keywords (namespace catalogia).",
      },
      {
        name: "addProductImage",
        method: "mutation",
        endpoint: "productCreateMedia → originalSource",
        kind: "write",
        fields: "originalSource (URL), alt, mediaContentType",
        purpose: "Publica uma foto gerada por IA como imagem real do produto.",
      },
      {
        name: "updateImageAltText",
        method: "mutation",
        endpoint: "fileUpdate",
        kind: "write",
        fields: "id (MediaImage), alt",
        purpose: "Publica alt-text numa imagem existente.",
      },
      {
        name: "testConnection",
        method: "query",
        endpoint: "{ shop { name } }",
        kind: "read",
        fields: "—",
        purpose: "Valida a credencial Shopify salva no painel de Integrações.",
      },
    ],
  },
  {
    key: "gsc",
    title: "Google Search Console",
    baseUrl: "https://searchconsole.googleapis.com/webmasters/v3",
    auth: "Bearer OAuth2 (access token renovado do refresh token salvo)",
    retry: "requestWithRetry compartilhado",
    operations: [
      {
        name: "queryByPage",
        method: "POST",
        endpoint: "/sites/{siteUrl}/searchAnalytics/query",
        kind: "read",
        fields: "dimension page → clicks, impressions, ctr, position",
        purpose:
          "Impressões/cliques/CTR/posição por página — sinal de priorização do Analyst, linha de base de SEO, e as " +
          "janelas antes/depois do painel de Impacto real (impact.agent.ts) — sempre consultado ao vivo, nunca " +
          "guardado numa tabela própria (GSC já retém ~16 meses de histórico diário).",
        caveat: "Casamento é só por URL/pathname — GSC não tem conceito de SKU.",
      },
      {
        name: "queryTopQueriesByPage",
        method: "POST",
        endpoint: "/sites/{siteUrl}/searchAnalytics/query",
        kind: "read",
        fields: "dimensions [page, query] → agrupado por página, top N por cliques/impressões",
        purpose:
          "Buscas reais que trazem gente pra cada página — passadas pro Content Enrichment (topSearchQueries) " +
          "pra priorizar termos que compradores de fato digitam em seoTitle/keywords/description, em vez da IA " +
          "inventar palavras-chave plausíveis.",
        caveat: "Mesmo casamento por URL/pathname que queryByPage.",
      },
      {
        name: "testConnection",
        method: "GET",
        endpoint: "/sites/{siteUrl}",
        kind: "read",
        fields: "—",
        purpose: "Valida a propriedade GSC conectada.",
      },
    ],
  },
  {
    key: "ga4",
    title: "Google Analytics 4",
    baseUrl: "https://analyticsdata.googleapis.com/v1beta (dados) e analyticsadmin (validação)",
    auth: "Bearer OAuth2 (access token renovado do refresh token salvo)",
    retry: "requestWithRetry compartilhado",
    operations: [
      {
        name: "runProductPageReport",
        method: "POST",
        endpoint: "/properties/{propertyId}:runReport",
        kind: "read",
        fields: "dimension pagePath → sessions, sessionConversionRate, totalRevenue",
        purpose:
          "Sessões/conversão/receita por página — fecha a ponta que o GSC não cobre (negócio, não só visibilidade); " +
          "mesmo uso duplo do queryByPage do GSC (priorização + janelas do painel de Impacto real, sempre ao vivo).",
        caveat: "Também casado só por pathname hoje — daria pra trocar pra dimensão itemId (SKU) se a loja já mandar item_id nos eventos de e-commerce.",
      },
      {
        name: "testConnection",
        method: "GET",
        endpoint: "/properties/{propertyId}",
        kind: "read",
        fields: "—",
        purpose: "Valida a propriedade GA4 conectada.",
      },
    ],
  },
  {
    key: "anthropic",
    title: "Anthropic (Claude)",
    baseUrl: "https://api.anthropic.com/v1/messages (via SDK)",
    auth: "API key (SDK)",
    retry: "Sem retry próprio neste client — cada chamada é tentada uma vez",
    operations: [
      {
        name: "enrichProductContent",
        method: "messages.create + tool forçado",
        endpoint: "submit_enriched_content",
        kind: "write",
        fields: "description, bullets, specs, FAQ, dados estruturados, SEO title/meta, keywords, tags, CTA, attributesPatch, featuredImageUrl",
        purpose: "Geração/reescrita de conteúdo — multimodal quando o nível Excelente pede foto embutida.",
      },
      {
        name: "evaluateContent",
        method: "messages.create + tool forçado",
        endpoint: "submit_evaluation",
        kind: "read",
        fields: "buyerConfidence, seoScore, conversionScore, dataConsistencyScore, geoAnswerableCount, catalogIssues, unsupportedClaims",
        purpose: "Juiz do score composto — mesma régua pro conteúdo original e o proposto.",
      },
      {
        name: "generateAltText",
        method: "messages.create (visão)",
        endpoint: "—",
        kind: "write",
        fields: "Texto de alt-text (máx. 125 caracteres)",
        purpose: "Alt-text de imagem de produto.",
      },
      {
        name: "testConnection",
        method: "messages.create",
        endpoint: "ping",
        kind: "read",
        fields: "—",
        purpose: "Valida a chave Anthropic salva.",
      },
    ],
  },
  {
    key: "openai",
    title: "OpenAI (GPT + Embeddings)",
    baseUrl: "https://api.openai.com/v1/responses e /v1/embeddings (via SDK)",
    auth: "API key (SDK)",
    retry: "Sem retry próprio neste client — cada chamada é tentada uma vez",
    operations: [
      {
        name: "enrichProductContent",
        method: "responses.create + tool forçado",
        endpoint: "submit_enriched_content",
        kind: "write",
        fields: "Mesmos campos do Claude",
        purpose: "Geração/reescrita de conteúdo (provedor alternativo, roteável por tarefa).",
      },
      {
        name: "evaluateContent",
        method: "responses.create + tool forçado",
        endpoint: "submit_evaluation",
        kind: "read",
        fields: "Mesmos campos do Claude",
        purpose: "Juiz do score composto (provedor alternativo).",
      },
      {
        name: "generateAltText",
        method: "responses.create (visão)",
        endpoint: "—",
        kind: "write",
        fields: "Texto de alt-text",
        purpose: "Alt-text de imagem — manda a URL da imagem direto, sem baixar bytes localmente.",
      },
      {
        name: "testConnection",
        method: "responses.create",
        endpoint: "ping",
        kind: "read",
        fields: "—",
        purpose: "Valida a chave OpenAI salva.",
      },
      {
        name: "embed (EmbeddingsClient)",
        method: "embeddings.create",
        endpoint: "/v1/embeddings",
        kind: "read",
        fields: "input: textos do produto → vetores de 1536 dimensões",
        purpose:
          "Gera embeddings pra detecção de produtos quase-duplicados (reaproveita conteúdo já aprovado em vez de gerar de novo) — nunca usado pra geração de conteúdo em si.",
        caveat: "Sempre via OpenAI, mesmo quando o provedor roteado pra enriquecimento é outro — opcional (sem conexão OpenAI, todo produto passa por geração completa).",
      },
    ],
  },
  {
    key: "gemini",
    title: "Google Gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/interactions (via SDK)",
    auth: "API key (SDK)",
    retry: "Retry próprio (3 tentativas, backoff 3s dobrando, teto 20s) — só 429/5xx; limit:0 nunca reage",
    operations: [
      {
        name: "enrichProductContent",
        method: "interactions.create + schema",
        endpoint: "response_format json schema",
        kind: "write",
        fields: "Mesmos campos do Claude/OpenAI",
        purpose: "Geração/reescrita de conteúdo (provedor alternativo).",
        caveat: "thinking_level:'minimal' é obrigatório — sem isso o modelo gasta o orçamento de tokens 'pensando' e trunca o JSON.",
      },
      {
        name: "evaluateContent",
        method: "interactions.create + schema",
        endpoint: "response_format json schema",
        kind: "read",
        fields: "Mesmos campos do Claude/OpenAI",
        purpose: "Juiz do score composto (provedor alternativo).",
      },
      {
        name: "generateAltText",
        method: "interactions.create (visão)",
        endpoint: "—",
        kind: "write",
        fields: "Texto de alt-text",
        purpose: "Alt-text de imagem.",
      },
      {
        name: "generateProductImage",
        method: "interactions.create (imagem)",
        endpoint: "response_format: image",
        kind: "write",
        fields: "Imagem gerada (base64) a partir de fotos de referência",
        purpose: "Único provedor dos 3 que gera imagem de verdade — nunca do zero, sempre a partir de fotos reais do produto.",
        caveat: "'delivery' explícito é rejeitado pela API — tem que omitir o campo. thinking_level só aceita low/high aqui, nunca minimal.",
      },
      {
        name: "verifyImageIntegrity",
        method: "interactions.create + schema (visão)",
        endpoint: "response_format json schema",
        kind: "read",
        fields: "sameProduct (boolean), notes",
        purpose: "Gate de integridade — segunda chamada independente confirmando que a imagem gerada é o mesmo produto.",
      },
      {
        name: "testConnection",
        method: "interactions.create",
        endpoint: "ping",
        kind: "read",
        fields: "—",
        purpose: "Valida a chave Gemini salva.",
      },
    ],
  },
  {
    key: "resend",
    title: "Resend (e-mail)",
    baseUrl: "resend.emails.send (via SDK)",
    auth: "API key (RESEND_API_KEY)",
    retry: "Sem retry próprio — uma tentativa",
    operations: [
      {
        name: "send (ResendEmailClient)",
        method: "resend.emails.send",
        endpoint: "—",
        kind: "write",
        fields: "from, to, subject, html",
        purpose: "Envia e-mail de redefinição de senha e de configuração de conta (convite de usuário).",
        caveat: "Sem RESEND_API_KEY/RESEND_FROM_EMAIL configurados, o link é retornado direto na resposta da API em vez de enviado por e-mail (fallback usado em dev).",
      },
    ],
  },
  {
    key: "web-fetch",
    title: "Referências externas (link de mercado / fabricante colado pelo usuário)",
    baseUrl: "URL fornecida pelo usuário — sem host fixo",
    auth: "Nenhuma — GET simples com um User-Agent identificável",
    retry: "Sem retry — falha de rede/HTTP vira erro mostrado na hora ao usuário; sem headless browser",
    operations: [
      {
        name: "fetchPageText (web-fetch.client.ts)",
        method: "GET",
        endpoint: "—",
        kind: "read",
        fields: "HTML bruto, reduzido a texto visível (tags/scripts/styles removidos)",
        purpose: "Busca a página que o usuário colou (referência de mercado por categoria, ou página do fabricante por produto), antes de qualquer extração por IA.",
        caveat: "Página cujo conteúdo principal só existe depois de JavaScript rodar (SPA pesado) volta com pouco texto — sinalizado como aviso na UI, não falha silenciosa.",
      },
      {
        name: "extractReferenceStructure (reference-structure.agent.ts)",
        method: "LLM (contentEnrichment routing)",
        endpoint: "—",
        kind: "read",
        fields: "wordCount, bulletCount, headingCount, hasFaq, hasSpecTable, hasWarrantySection, mentionsInstallation",
        purpose: "Extrai só sinais ESTRUTURAIS do texto de um anúncio de referência de mercado (nunca reproduz o texto em si) — alimenta o DNA de conteúdo por categoria por consenso entre vários links.",
      },
      {
        name: "extractManufacturerFacts (reference-facts.agent.ts)",
        method: "LLM (contentEnrichment routing)",
        endpoint: "—",
        kind: "read",
        fields: "Array de {key, value} — fatos técnicos objetivos (specs, dimensões, material, garantia)",
        purpose: "Extrai só FATOS objetivos da página do fabricante de UM produto específico (oposto da extração de estrutura) — grounding contra alucinação, nunca copia texto de marketing.",
      },
    ],
  },
];
